#!/usr/bin/env python3
"""
Anti-UAV Control Center — Main Device Launcher
Simplified GUI: 3 primary fields, collapsible Advanced section,
live service health panel, and a Certs tab with cert wizard.
"""

import os
import subprocess
import threading
import tkinter as tk
import webbrowser
from tkinter import font as tkfont, scrolledtext, ttk

DOCKER_DIR = os.path.join(os.path.dirname(__file__), "docker")
ENV_FILE = os.path.join(DOCKER_DIR, ".env")
CERTS_SCRIPT = os.path.join(os.path.dirname(__file__), "certs", "gen_certs.sh")
SECRETS_DIR = os.path.join(os.path.dirname(__file__), "secrets")

DEFAULTS = {
    "MQTT_PORT": "8883",
    "CONTROL_CENTER_PORT": "8080",
    "REMOTE_ACCESS_MODE": "local",
    "AGGREGATION_PORT": "8001",
    "SIGNALING_PORT": "8090",
    "HTTPS_TOKEN": "changeme",
    "RADAR_ENABLED": "false",
    "JWT_SECRET": "change-me-in-production",
    "JWT_TTL_HOURS": "8",
    "BOOTSTRAP_ADMIN_USERNAME": "admin",
    "BOOTSTRAP_ADMIN_PASSWORD": "changeme",
}

SERVICES = ["mosquitto", "aggregation", "control-center", "signaling", "ha_bridge"]

BG = "#0f172a"; CARD = "#1e293b"; ACC = "#3b82f6"; FG = "#f1f5f9"; DIM = "#94a3b8"
GREEN = "#22c55e"; RED = "#ef4444"; AMBER = "#f59e0b"


def load_env():
    values = dict(DEFAULTS)
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    values[k.strip()] = v.strip()
    return values


def save_env(values):
    os.makedirs(DOCKER_DIR, exist_ok=True)
    with open(ENV_FILE, "w") as f:
        f.write("# Auto-generated by launcher_main.py\n")
        for k, v in values.items():
            f.write(f"{k}={v}\n")


def run_cmd(cmd, cwd, log_widget):
    def _append(text):
        log_widget.after(0, lambda: _append_safe(text))

    def _append_safe(text):
        log_widget.configure(state="normal")
        log_widget.insert(tk.END, text)
        log_widget.see(tk.END)
        log_widget.configure(state="disabled")

    try:
        proc = subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT, text=True, bufsize=1)
        for line in proc.stdout:
            _append(line)
        proc.wait()
        return proc.returncode
    except FileNotFoundError as e:
        _append(f"\nERROR: {e}\n")
        return 1


def get_service_status():
    """Return dict of service_name → 'running'|'stopped'|'unknown'."""
    try:
        result = subprocess.run(
            ["docker", "compose", "ps", "--format", "{{.Service}}\t{{.State}}"],
            cwd=DOCKER_DIR, capture_output=True, text=True, timeout=5
        )
        status = {}
        for line in result.stdout.strip().splitlines():
            parts = line.split("\t")
            if len(parts) == 2:
                status[parts[0]] = parts[1]
        return status
    except Exception:
        return {}


def read_cert_info():
    """Return list of (filename, cn, expiry, valid) for certs in secrets/."""
    import ssl, datetime
    certs = []
    if not os.path.exists(SECRETS_DIR):
        return certs
    for fname in sorted(os.listdir(SECRETS_DIR)):
        if not fname.endswith(".crt"):
            continue
        path = os.path.join(SECRETS_DIR, fname)
        try:
            cert = ssl._ssl._test_decode_cert(path)
            subject = dict(x[0] for x in cert.get("subject", ()))
            cn = subject.get("commonName", fname)
            not_after = cert.get("notAfter", "")
            try:
                exp = datetime.datetime.strptime(not_after, "%b %d %H:%M:%S %Y %Z")
                valid = exp > datetime.datetime.utcnow()
                expiry_str = exp.strftime("%Y-%m-%d")
            except Exception:
                valid = True
                expiry_str = not_after
            certs.append((fname, cn, expiry_str, valid))
        except Exception:
            certs.append((fname, "?", "?", True))
    return certs


class MainLauncher(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Anti-UAV — Main Device Launcher")
        self.configure(bg=BG)
        self.resizable(True, True)
        self._running = False
        self._health_job = None
        self._build_ui()
        self._schedule_health_poll()

    def _build_ui(self):
        title_font = tkfont.Font(family="monospace", size=13, weight="bold")
        label_font = tkfont.Font(family="monospace", size=10)
        btn_font = tkfont.Font(family="monospace", size=10, weight="bold")

        tk.Label(self, text="Anti-UAV Control Center — Main Device",
                 bg=BG, fg=FG, font=title_font).pack(pady=(14, 2))

        # Notebook (Stack tab + Certs tab)
        nb = ttk.Notebook(self)
        nb.pack(fill="both", expand=True, padx=16, pady=8)

        stack_frame = tk.Frame(nb, bg=BG)
        certs_frame = tk.Frame(nb, bg=BG)
        nb.add(stack_frame, text="  Stack  ")
        nb.add(certs_frame, text="  Certs  ")

        self._build_stack_tab(stack_frame, label_font, btn_font)
        self._build_certs_tab(certs_frame, label_font, btn_font)

    # ── Stack tab ──────────────────────────────────────────────────────────

    def _build_stack_tab(self, parent, label_font, btn_font):
        env = load_env()
        self._vars = {}

        # Primary fields
        primary = tk.Frame(parent, bg="#1e293b", padx=14, pady=10)
        primary.pack(fill="x", padx=8, pady=4)

        primary_fields = [
            ("MQTT Port", "MQTT_PORT"),
            ("Control Center Port", "CONTROL_CENTER_PORT"),
            ("Remote Access Mode", "REMOTE_ACCESS_MODE"),
        ]
        for r, (lbl, key) in enumerate(primary_fields):
            tk.Label(primary, text=lbl + ":", bg="#1e293b", fg=DIM,
                     font=label_font, anchor="w", width=22).grid(row=r, column=0, sticky="w", pady=3)
            var = tk.StringVar(value=env.get(key, DEFAULTS.get(key, "")))
            self._vars[key] = var
            tk.Entry(primary, textvariable=var, bg=BG, fg=FG, insertbackground=FG,
                     font=label_font, relief="flat", width=26).grid(row=r, column=1, sticky="ew", padx=(8, 0), pady=3)
        primary.columnconfigure(1, weight=1)

        # Advanced toggle
        self._adv_visible = tk.BooleanVar(value=False)
        adv_btn = tk.Button(parent, text="▶ Advanced", bg=BG, fg=DIM, font=label_font,
                            relief="flat", anchor="w", command=self._toggle_advanced)
        adv_btn.pack(fill="x", padx=8)
        self._adv_btn = adv_btn

        self._adv_frame = tk.Frame(parent, bg="#1e293b", padx=14, pady=10)
        adv_fields = [
            ("Aggregation Port", "AGGREGATION_PORT"),
            ("Signaling Port", "SIGNALING_PORT"),
            ("HTTPS Token", "HTTPS_TOKEN"),
            ("Radar Enabled", "RADAR_ENABLED"),
            ("JWT Secret", "JWT_SECRET"),
            ("Bootstrap Admin", "BOOTSTRAP_ADMIN_USERNAME"),
            ("Bootstrap Password", "BOOTSTRAP_ADMIN_PASSWORD"),
        ]
        for r, (lbl, key) in enumerate(adv_fields):
            tk.Label(self._adv_frame, text=lbl + ":", bg="#1e293b", fg=DIM,
                     font=label_font, anchor="w", width=22).grid(row=r, column=0, sticky="w", pady=2)
            var = tk.StringVar(value=env.get(key, DEFAULTS.get(key, "")))
            self._vars[key] = var
            tk.Entry(self._adv_frame, textvariable=var, bg=BG, fg=FG, insertbackground=FG,
                     font=label_font, relief="flat", width=26).grid(row=r, column=1, sticky="ew", padx=(8, 0), pady=2)
        self._adv_frame.columnconfigure(1, weight=1)

        # Service health panel
        health_frame = tk.Frame(parent, bg="#1e293b", padx=14, pady=8)
        health_frame.pack(fill="x", padx=8, pady=4)
        tk.Label(health_frame, text="Service Health", bg="#1e293b", fg=DIM,
                 font=label_font).grid(row=0, column=0, columnspan=len(SERVICES), sticky="w", pady=(0, 4))
        self._health_labels = {}
        for i, svc in enumerate(SERVICES):
            dot = tk.Label(health_frame, text="●", bg="#1e293b", fg=DIM, font=label_font)
            dot.grid(row=1, column=i * 2, padx=(0, 2))
            lbl = tk.Label(health_frame, text=svc, bg="#1e293b", fg=DIM, font=label_font)
            lbl.grid(row=1, column=i * 2 + 1, padx=(0, 12))
            self._health_labels[svc] = dot

        # Buttons
        btn_frame = tk.Frame(parent, bg=BG)
        btn_frame.pack(fill="x", padx=8, pady=6)

        self._start_btn = tk.Button(btn_frame, text="▶ Start Stack", bg=ACC, fg="#fff",
                                    font=btn_font, relief="flat", padx=12, pady=6, command=self._start)
        self._start_btn.pack(side="left", padx=(0, 6))

        self._stop_btn = tk.Button(btn_frame, text="■ Stop", bg=RED, fg="#fff",
                                   font=btn_font, relief="flat", padx=12, pady=6,
                                   command=self._stop, state="disabled")
        self._stop_btn.pack(side="left", padx=(0, 6))

        tk.Button(btn_frame, text="🌐 Open UI", bg="#475569", fg=FG, font=btn_font,
                  relief="flat", padx=10, pady=6, command=self._open_ui).pack(side="left", padx=(0, 6))

        tk.Button(btn_frame, text="Save Config", bg="#475569", fg=FG, font=btn_font,
                  relief="flat", padx=10, pady=6, command=self._save).pack(side="left")

        self._status_lbl = tk.Label(btn_frame, text="● Stopped", bg=BG, fg=RED, font=label_font)
        self._status_lbl.pack(side="left", padx=12)

        # Log
        tk.Label(parent, text="Output:", bg=BG, fg=DIM, font=label_font, anchor="w").pack(fill="x", padx=8)
        self._log = scrolledtext.ScrolledText(parent, bg="#020617", fg="#86efac",
                                              font=("monospace", 9), height=10,
                                              state="disabled", relief="flat")
        self._log.pack(fill="both", expand=True, padx=8, pady=(0, 8))

    def _toggle_advanced(self):
        if self._adv_visible.get():
            self._adv_frame.pack_forget()
            self._adv_visible.set(False)
            self._adv_btn.configure(text="▶ Advanced")
        else:
            self._adv_frame.pack(fill="x", padx=8, pady=2)
            self._adv_visible.set(True)
            self._adv_btn.configure(text="▼ Advanced")

    # ── Certs tab ──────────────────────────────────────────────────────────

    def _build_certs_tab(self, parent, label_font, btn_font):
        form = tk.Frame(parent, bg="#1e293b", padx=14, pady=10)
        form.pack(fill="x", padx=8, pady=4)

        tk.Label(form, text="Server IP:", bg="#1e293b", fg=DIM, font=label_font, width=14, anchor="w").grid(row=0, column=0, sticky="w", pady=3)
        self._cert_server_ip = tk.StringVar(value="")
        tk.Entry(form, textvariable=self._cert_server_ip, bg=BG, fg=FG, insertbackground=FG,
                 font=label_font, relief="flat", width=24).grid(row=0, column=1, sticky="ew", padx=(8, 0), pady=3)

        tk.Label(form, text="Device IDs:", bg="#1e293b", fg=DIM, font=label_font, width=14, anchor="w").grid(row=1, column=0, sticky="w", pady=3)
        self._cert_device_ids = tk.StringVar(value="edge-01")
        tk.Entry(form, textvariable=self._cert_device_ids, bg=BG, fg=FG, insertbackground=FG,
                 font=label_font, relief="flat", width=24).grid(row=1, column=1, sticky="ew", padx=(8, 0), pady=3)
        form.columnconfigure(1, weight=1)

        tk.Button(parent, text="Generate Certs", bg=ACC, fg="#fff", font=btn_font,
                  relief="flat", padx=12, pady=6, command=self._generate_certs).pack(anchor="w", padx=8, pady=4)

        # Cert status table
        self._cert_table_frame = tk.Frame(parent, bg="#1e293b")
        self._cert_table_frame.pack(fill="x", padx=8, pady=4)
        self._refresh_cert_table()

        # Cert log
        tk.Label(parent, text="Output:", bg=BG, fg=DIM, font=label_font, anchor="w").pack(fill="x", padx=8)
        self._cert_log = scrolledtext.ScrolledText(parent, bg="#020617", fg="#86efac",
                                                   font=("monospace", 9), height=8,
                                                   state="disabled", relief="flat")
        self._cert_log.pack(fill="both", expand=True, padx=8, pady=(0, 8))

    def _refresh_cert_table(self):
        for w in self._cert_table_frame.winfo_children():
            w.destroy()
        label_font = tkfont.Font(family="monospace", size=9)
        certs = read_cert_info()
        if not certs:
            tk.Label(self._cert_table_frame, text="No certificates found in secrets/",
                     bg="#1e293b", fg=DIM, font=label_font).pack(padx=8, pady=4)
            return
        headers = ["File", "CN", "Expiry", "Status", "Action"]
        for c, h in enumerate(headers):
            tk.Label(self._cert_table_frame, text=h, bg="#1e293b", fg=DIM,
                     font=label_font, width=14, anchor="w").grid(row=0, column=c, padx=4, pady=2)
        for r, (fname, cn, expiry, valid) in enumerate(certs, start=1):
            tk.Label(self._cert_table_frame, text=fname, bg="#1e293b", fg="#f1f5f9",
                     font=label_font, anchor="w").grid(row=r, column=0, padx=4, pady=1, sticky="w")
            tk.Label(self._cert_table_frame, text=cn, bg="#1e293b", fg="#f1f5f9",
                     font=label_font, anchor="w").grid(row=r, column=1, padx=4, pady=1, sticky="w")
            tk.Label(self._cert_table_frame, text=expiry, bg="#1e293b", fg="#f1f5f9",
                     font=label_font, anchor="w").grid(row=r, column=2, padx=4, pady=1, sticky="w")
            status_color = "#22c55e" if valid else "#ef4444"
            status_text = "✓ Valid" if valid else "✗ Expired"
            tk.Label(self._cert_table_frame, text=status_text, bg="#1e293b", fg=status_color,
                     font=label_font).grid(row=r, column=3, padx=4, pady=1)
            tk.Button(self._cert_table_frame, text="Copy →", bg="#334155", fg="#f1f5f9",
                      font=label_font, relief="flat", padx=4,
                      command=lambda f=fname: self._copy_cert_to_device(f)).grid(row=r, column=4, padx=4, pady=1)

    def _generate_certs(self):
        server_ip = self._cert_server_ip.get().strip()
        device_ids = self._cert_device_ids.get().strip()
        if not server_ip or not device_ids:
            self._cert_log_line("⚠ Please enter Server IP and Device IDs\n")
            return

        def _run():
            env = {**os.environ, "SERVER_IP": server_ip, "DEVICE_IDS": device_ids, "FORCE": "1"}
            self._cert_log_line(f"$ FORCE=1 SERVER_IP={server_ip} DEVICE_IDS={device_ids} bash certs/gen_certs.sh\n")
            try:
                proc = subprocess.Popen(
                    ["bash", CERTS_SCRIPT], cwd=os.path.dirname(__file__),
                    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, env=env
                )
                for line in proc.stdout:
                    self._cert_log_line(line)
                proc.wait()
                self._cert_log_line("✓ Done\n")
                self.after(0, self._refresh_cert_table)
            except Exception as e:
                self._cert_log_line(f"ERROR: {e}\n")

        threading.Thread(target=_run, daemon=True).start()

    def _copy_cert_to_device(self, fname):
        win = tk.Toplevel(self)
        win.title("Copy to Device")
        win.configure(bg=BG)
        label_font = tkfont.Font(family="monospace", size=10)
        tk.Label(win, text="Edge Device IP:", bg=BG, fg=DIM, font=label_font).pack(padx=16, pady=(12, 4))
        ip_var = tk.StringVar()
        tk.Entry(win, textvariable=ip_var, bg="#1e293b", fg="#f1f5f9", font=label_font,
                 relief="flat", width=20).pack(padx=16, pady=4)

        def _do_copy():
            ip = ip_var.get().strip()
            if not ip:
                return
            win.destroy()
            # Determine which files to copy based on cert name
            base = fname.replace(".crt", "")
            files = [
                os.path.join(SECRETS_DIR, "ca.crt"),
                os.path.join(SECRETS_DIR, f"{base}.crt"),
                os.path.join(SECRETS_DIR, f"{base}.key"),
            ]
            for f in files:
                if os.path.exists(f):
                    cmd = ["scp", f, f"user@{ip}:~/Projects/UAV/UAV/secrets/"]
                    self._log_line(f"$ {' '.join(cmd)}\n")
                    run_cmd(cmd, os.path.dirname(__file__), self._cert_log)
            self._cert_log_line("✓ Copy complete\n")

        tk.Button(win, text="Copy", bg=ACC, fg="#fff", font=label_font,
                  relief="flat", padx=12, pady=6, command=_do_copy).pack(padx=16, pady=8)

    def _cert_log_line(self, text):
        self.after(0, lambda: self._cert_log_append(text))

    def _cert_log_append(self, text):
        self._cert_log.configure(state="normal")
        self._cert_log.insert(tk.END, text)
        self._cert_log.see(tk.END)
        self._cert_log.configure(state="disabled")

    # ── Stack controls ─────────────────────────────────────────────────────

    def _save(self):
        values = {k: v.get() for k, v in self._vars.items()}
        save_env(values)
        self._log_line("✓ Config saved\n")

    def _open_ui(self):
        port = self._vars.get("CONTROL_CENTER_PORT", tk.StringVar(value="8080")).get()
        webbrowser.open(f"http://localhost:{port}")

    def _start(self):
        self._save()
        self._start_btn.configure(state="disabled")
        self._stop_btn.configure(state="normal")
        self._set_status("● Starting…", AMBER)

        def _run():
            rc = run_cmd(["docker", "compose", "--env-file", ".env", "up", "-d", "--build"],
                         cwd=DOCKER_DIR, log_widget=self._log)
            if rc == 0:
                self._set_status("● Running", GREEN)
                self._running = True
                port = self._vars.get("CONTROL_CENTER_PORT", tk.StringVar(value="8080")).get()
                self._log_line(f"\n✓ Stack started. Open http://localhost:{port}\n")
            else:
                self._set_status("● Error", RED)
                self.after(0, lambda: self._start_btn.configure(state="normal"))
                self.after(0, lambda: self._stop_btn.configure(state="disabled"))

        threading.Thread(target=_run, daemon=True).start()

    def _stop(self):
        self._stop_btn.configure(state="disabled")
        self._set_status("● Stopping…", AMBER)

        def _run():
            run_cmd(["docker", "compose", "down"], cwd=DOCKER_DIR, log_widget=self._log)
            self._set_status("● Stopped", RED)
            self.after(0, lambda: self._start_btn.configure(state="normal"))
            self._running = False

        threading.Thread(target=_run, daemon=True).start()

    def _log_line(self, text):
        self.after(0, lambda: self._log_append(text))

    def _log_append(self, text):
        self._log.configure(state="normal")
        self._log.insert(tk.END, text)
        self._log.see(tk.END)
        self._log.configure(state="disabled")

    def _set_status(self, text, color):
        self.after(0, lambda: self._status_lbl.configure(text=text, fg=color))

    # ── Health polling ─────────────────────────────────────────────────────

    def _schedule_health_poll(self):
        self._poll_health()
        self._health_job = self.after(5000, self._schedule_health_poll)

    def _poll_health(self):
        def _run():
            status = get_service_status()
            self.after(0, lambda: self._update_health_dots(status))
        threading.Thread(target=_run, daemon=True).start()

    def _update_health_dots(self, status):
        for svc, dot in self._health_labels.items():
            state = status.get(svc, "")
            if "running" in state.lower():
                dot.configure(fg=GREEN)
            elif state:
                dot.configure(fg=RED)
            else:
                dot.configure(fg=DIM)


if __name__ == "__main__":
    app = MainLauncher()
    try:
        app.mainloop()
    except Exception as e:
        import traceback
        print("Launcher crashed:", traceback.format_exc())
