#!/usr/bin/env python3
"""
UAV Control Center — Main Device Launcher GUI
Run on the MAIN laptop (the one running Docker).

Lets you configure ports/IPs, writes docker/.env, then starts/stops
the Docker Compose stack.
"""

import os
import subprocess
import threading
import tkinter as tk
from tkinter import font as tkfont
from tkinter import messagebox, scrolledtext

DOCKER_DIR = os.path.join(os.path.dirname(__file__), "docker")
ENV_FILE   = os.path.join(DOCKER_DIR, ".env")

DEFAULTS = {
    "MQTT_PORT":            "8883",
    "AGGREGATION_PORT":     "8001",
    "CONTROL_CENTER_PORT":  "8080",
    "SIGNALING_PORT":       "8090",
    "REMOTE_ACCESS_MODE":   "local",
    "HTTPS_TOKEN":          "changeme",
    "RADAR_ENABLED":        "false",
    "TILE_SERVER_URL":      "http://localhost:8070",
    "MQTT_AUTH_MODE":       "cert",
}

# UFW ports to open (proto)
UFW_PORTS = [
    ("8883", "tcp"),   # MQTT
    ("8080", "tcp"),   # Control Center
    ("8090", "tcp"),   # Signaling
    ("8001", "tcp"),   # Aggregation (internal, but open for edge direct access)
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_env() -> dict:
    values = dict(DEFAULTS)
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    values[k.strip()] = v.strip()
    return values


def save_env(values: dict) -> None:
    os.makedirs(DOCKER_DIR, exist_ok=True)
    lines = ["# Auto-generated by launcher_main.py\n"]
    for k, v in values.items():
        lines.append(f"{k}={v}\n")
    with open(ENV_FILE, "w") as f:
        f.writelines(lines)


def run_cmd(cmd: list, cwd: str, log_widget: scrolledtext.ScrolledText) -> int:
    """Run a command, streaming output to the log widget (thread-safe via after())."""
    def _append(text):
        log_widget.after(0, _append_safe, text)

    def _append_safe(text):
        log_widget.configure(state="normal")
        log_widget.insert(tk.END, text)
        log_widget.see(tk.END)
        log_widget.configure(state="disabled")

    try:
        proc = subprocess.Popen(
            cmd, cwd=cwd,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, bufsize=1,
        )
        for line in proc.stdout:
            _append(line)
        proc.wait()
        return proc.returncode
    except FileNotFoundError as e:
        _append(f"\nERROR: {e}\n")
        return 1


# ---------------------------------------------------------------------------
# Main window
# ---------------------------------------------------------------------------

class MainLauncher(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Anti-UAV — Main Device Launcher")
        self.resizable(True, True)
        self.configure(bg="#0f172a")
        self._build_ui()
        self._running = False

    def _build_ui(self):
        BG   = "#0f172a"
        CARD = "#1e293b"
        ACC  = "#3b82f6"
        FG   = "#f1f5f9"
        DIM  = "#94a3b8"

        title_font = tkfont.Font(family="monospace", size=14, weight="bold")
        label_font = tkfont.Font(family="monospace", size=10)
        btn_font   = tkfont.Font(family="monospace", size=11, weight="bold")

        # ── Title ──
        tk.Label(self, text="Anti-UAV Control Center — Main Device",
                 bg=BG, fg=FG, font=title_font).pack(pady=(16, 4))
        tk.Label(self, text="Configure ports, then start the Docker stack.",
                 bg=BG, fg=DIM, font=label_font).pack(pady=(0, 12))

        # ── Config card ──
        card = tk.Frame(self, bg=CARD, padx=16, pady=12)
        card.pack(fill="x", padx=20, pady=4)

        env = load_env()
        self._vars = {}

        fields = [
            ("MQTT Port",            "MQTT_PORT"),
            ("Aggregation Port",     "AGGREGATION_PORT"),
            ("Control Center Port",  "CONTROL_CENTER_PORT"),
            ("Signaling Port",       "SIGNALING_PORT"),
            ("Remote Access Mode",   "REMOTE_ACCESS_MODE"),
            ("HTTPS Token",          "HTTPS_TOKEN"),
            ("Radar Enabled",        "RADAR_ENABLED"),
        ]

        for row, (label, key) in enumerate(fields):
            tk.Label(card, text=label + ":", bg=CARD, fg=DIM,
                     font=label_font, anchor="w", width=22).grid(
                row=row, column=0, sticky="w", pady=3)
            var = tk.StringVar(value=env.get(key, DEFAULTS.get(key, "")))
            self._vars[key] = var
            tk.Entry(card, textvariable=var, bg="#0f172a", fg=FG,
                     insertbackground=FG, font=label_font,
                     relief="flat", width=28).grid(
                row=row, column=1, sticky="ew", padx=(8, 0), pady=3)

        card.columnconfigure(1, weight=1)

        # ── UFW button ──
        btn_frame = tk.Frame(self, bg=BG)
        btn_frame.pack(fill="x", padx=20, pady=8)

        tk.Button(btn_frame, text="Open Firewall Ports (UFW)",
                  bg="#475569", fg=FG, font=btn_font, relief="flat",
                  padx=12, pady=6,
                  command=self._open_ports).pack(side="left", padx=(0, 8))

        tk.Button(btn_frame, text="Save Config",
                  bg="#475569", fg=FG, font=btn_font, relief="flat",
                  padx=12, pady=6,
                  command=self._save).pack(side="left", padx=(0, 8))

        # ── Start / Stop ──
        ctrl_frame = tk.Frame(self, bg=BG)
        ctrl_frame.pack(fill="x", padx=20, pady=4)

        self._start_btn = tk.Button(
            ctrl_frame, text="▶  Start Stack",
            bg=ACC, fg="#fff", font=btn_font, relief="flat",
            padx=16, pady=8, command=self._start)
        self._start_btn.pack(side="left", padx=(0, 8))

        self._stop_btn = tk.Button(
            ctrl_frame, text="■  Stop Stack",
            bg="#ef4444", fg="#fff", font=btn_font, relief="flat",
            padx=16, pady=8, command=self._stop, state="disabled")
        self._stop_btn.pack(side="left")

        self._status_lbl = tk.Label(ctrl_frame, text="● Stopped",
                                    bg=BG, fg="#ef4444", font=label_font)
        self._status_lbl.pack(side="left", padx=16)

        # ── Log ──
        tk.Label(self, text="Output:", bg=BG, fg=DIM,
                 font=label_font, anchor="w").pack(fill="x", padx=20)
        self._log = scrolledtext.ScrolledText(
            self, bg="#020617", fg="#86efac", font=("monospace", 9),
            height=18, state="disabled", relief="flat")
        self._log.pack(fill="both", expand=True, padx=20, pady=(0, 16))

    # ------------------------------------------------------------------

    def _save(self):
        values = {k: v.get() for k, v in self._vars.items()}
        save_env(values)
        self._log_line("✓ Config saved to docker/.env\n")

    def _open_ports(self):
        def _run():
            for port, proto in UFW_PORTS:
                # Use the current value if the user changed a port
                if port == "8883":
                    port = self._vars.get("MQTT_PORT", tk.StringVar(value=port)).get()
                elif port == "8080":
                    port = self._vars.get("CONTROL_CENTER_PORT", tk.StringVar(value=port)).get()
                elif port == "8090":
                    port = self._vars.get("SIGNALING_PORT", tk.StringVar(value=port)).get()
                elif port == "8001":
                    port = self._vars.get("AGGREGATION_PORT", tk.StringVar(value=port)).get()
                cmd = ["sudo", "ufw", "allow", f"{port}/{proto}"]
                self._log_line(f"$ {' '.join(cmd)}\n")
                rc = run_cmd(cmd, cwd=os.path.dirname(__file__), log_widget=self._log)
                if rc != 0:
                    self._log_line(f"  ⚠ ufw returned {rc} — you may need to run manually\n")
            run_cmd(["sudo", "ufw", "reload"], cwd=os.path.dirname(__file__), log_widget=self._log)
            self._log_line("✓ Firewall rules applied\n")
        threading.Thread(target=_run, daemon=True).start()

    def _start(self):
        self._save()
        self._start_btn.configure(state="disabled")
        self._stop_btn.configure(state="normal")
        self._set_status("● Starting…", "#fbbf24")

        def _run():
            rc = run_cmd(
                ["docker", "compose", "--env-file", ".env", "up", "-d", "--build"],
                cwd=DOCKER_DIR, log_widget=self._log,
            )
            if rc == 0:
                self._set_status("● Running", "#22c55e")
                self._log_line("\n✓ Stack started. Open http://localhost:"
                               + self._vars["CONTROL_CENTER_PORT"].get() + "\n")
                self._running = True
            else:
                self._set_status("● Error", "#ef4444")
                self.after(0, lambda: self._start_btn.configure(state="normal"))
                self.after(0, lambda: self._stop_btn.configure(state="disabled"))

        threading.Thread(target=_run, daemon=True).start()

    def _stop(self):
        self._stop_btn.configure(state="disabled")
        self._set_status("● Stopping…", "#fbbf24")

        def _run():
            run_cmd(["docker", "compose", "down"],
                    cwd=DOCKER_DIR, log_widget=self._log)
            self._set_status("● Stopped", "#ef4444")
            self.after(0, lambda: self._start_btn.configure(state="normal"))
            self._running = False

        threading.Thread(target=_run, daemon=True).start()

    def _log_line(self, text):
        self.after(0, self._log_line_safe, text)

    def _log_line_safe(self, text):
        self._log.configure(state="normal")
        self._log.insert(tk.END, text)
        self._log.see(tk.END)
        self._log.configure(state="disabled")

    def _set_status(self, text, color):
        self.after(0, lambda: self._status_lbl.configure(text=text, fg=color))


if __name__ == "__main__":
    app = MainLauncher()
    try:
        app.mainloop()
    except Exception as e:
        import traceback
        print("Launcher crashed:", traceback.format_exc())
