"""Manual_Generator — writes MANUAL.md at project root with all required sections.

Requirements: 14.1, 14.2, 14.4, 14.5
"""
from __future__ import annotations

from pathlib import Path

from anti_uav.utils import atomic_write

_MANUAL_CONTENT = """\
# Anti-UAV Dataset Management and YOLO Training — User Manual

## Project Overview

This project provides an end-to-end pipeline for detecting unmanned aerial vehicles (UAVs)
using YOLO-based object detection models. The system handles three canonical object classes:

- **Bird** — naturally occurring airborne objects that may be confused with drones
- **Drone** — small consumer or commercial unmanned aerial vehicles
- **UAV** — broader category of unmanned aerial vehicles including military-grade platforms

The pipeline covers dataset inspection, annotation normalisation, dataset merging,
model training, validation, run documentation, and multi-run comparison. Remote training
on Google Colab and Kaggle is supported via the Colab Bridge component.

## Folder Structure

The project uses the following top-level directory layout:

```
<project_root>/
├── datasets/           Raw source datasets (one sub-folder per dataset)
├── merged_dataset/     Output of the Dataset Merger; contains data.yaml and split folders
├── training/           One run_<date>_<time>_<variant>/ sub-folder per training run
├── documentations/     Per-run Markdown documentation files
└── comparison/         Comparison reports (.md and .csv) and IoU sensitivity plots
```

Each directory contains a `README.md` stub created by `initialize_project_dirs`.

- `datasets/` — place raw ZIP archives or extracted dataset folders here before inspection.
- `merged_dataset/` — produced automatically; do not edit manually.
- `training/` — each run sub-folder contains `train_config.yaml`, `results.json`,
  `weights/best.pt`, `weights/last.pt`, and a `plots/` directory.
- `documentations/` — one `.md` file per completed run, generated by Run_Documenter.
- `comparison/` — generated by Run_Comparator; contains `comparison_report.md`,
  `comparison_report.csv`, and `iou_sensitivity.png`.

## Step-by-Step Procedure

Follow these numbered steps to run the full workflow from raw data to a trained model.

1. **Initialise project directories** — run `anti-uav` (no subcommand) or call
   `initialize_project_dirs(root)` to create the folder structure above.
2. **Inspect datasets** — run `anti-uav inspect <path>` for each source dataset.
   Review `inspection_report.json` and address any errors listed in `inspection_errors.log`.
3. **Review annotations** — run `anti-uav review <dataset_path>` to open the GUI reviewer.
   Stage unwanted images for deletion, remap non-canonical labels, and save changes.
4. **Normalise class labels** — run `anti-uav normalize <dataset_path> --mapping mapping.json`
   to rewrite all annotation files using the three canonical class names.
5. **Merge datasets** — run `anti-uav merge <src1> <src2> ... --output merged_dataset/`
   to combine sources, deduplicate by SHA-256, and produce `data.yaml`.
6. **Train the model** — run `anti-uav train --config train_config.yaml` (local) or use
   one of the remote backends below.
7. **Document the run** — run `anti-uav document <run_dir>` to generate a Markdown report
   in `documentations/`.
8. **Compare runs** — run `anti-uav compare <run1> <run2> ...` to produce a ranked
   comparison report in `comparison/`.

### Google Colab

1. Authenticate with Google: `anti-uav colab --backend colab --auth oauth2`
2. Upload the merged dataset to Google Drive:
   `anti-uav colab upload --source merged_dataset/ --drive-folder AntiUAV`
3. Generate and upload the training notebook:
   `anti-uav colab generate-notebook --backend colab --config train_config.yaml`
4. Open the uploaded notebook in Google Colab and run all cells, or trigger execution
   via the Drive API.
5. Download results: `anti-uav colab download --drive-folder AntiUAV/training/`
6. Continue from step 7 (Document the run) above.

### Kaggle

1. Place your `kaggle.json` API token in `~/.kaggle/kaggle.json`.
2. Upload the merged dataset as a Kaggle dataset:
   `anti-uav colab --backend kaggle upload-dataset --source merged_dataset/`
3. Generate and push the training kernel:
   `anti-uav colab --backend kaggle push-kernel --config train_config.yaml`
4. The kernel is polled automatically every 30 seconds (9-hour timeout).
   Partial outputs are downloaded on timeout with `completed=False` in `results.json`.
5. Download kernel outputs: `anti-uav colab --backend kaggle download-output`
6. Continue from step 7 (Document the run) above.

## Trained Weights Guide

After a successful training run the weights are saved under:

```
training/run_<YYYYMMDD>_<HHMMSS>_<variant>/weights/
├── best.pt   — checkpoint with the highest validation mAP@0.5:0.95
└── last.pt   — checkpoint from the final training epoch
```

**Loading weights with the Ultralytics API:**

```python
from ultralytics import YOLO

model = YOLO("training/run_20260101_120000_yolo26s/weights/best.pt")
```

**Running inference on a single image:**

```python
results = model.predict("path/to/image.jpg", conf=0.25, iou=0.45)
for r in results:
    print(r.boxes)   # bounding boxes, classes, confidences
    r.show()         # display annotated image
```

**Running inference on a directory:**

```python
results = model.predict("path/to/images/", save=True, project="runs/detect")
```

Use `best.pt` for deployment. Use `last.pt` only to resume training from the final epoch.

## Results Interpretation

The following metrics are reported in `results.json` and the run documentation:

| Metric | Description |
|---|---|
| **mAP@0.5** | Mean Average Precision at IoU threshold 0.5. Primary detection quality metric. |
| **mAP@0.5:0.95** | Mean AP averaged over IoU thresholds 0.50–0.95 (step 0.05). Stricter localisation measure. |
| **Precision** | Fraction of detections that are correct (TP / (TP + FP)). |
| **Recall** | Fraction of ground-truth objects detected (TP / (TP + FN)). |
| **F1** | Harmonic mean of Precision and Recall. |
| **Small-object mAP** | Per-class mAP@0.5 restricted to bounding boxes with area < 32×32 px. |
| **False Positive Rate** | Rate of spurious detections on background patches. |

**PR Curves** — Precision-Recall curves are saved per canonical class in `plots/`.
A curve that stays high across all recall values indicates a well-calibrated model.

**IoU Sensitivity Plots** — generated by Run_Comparator; show how mAP degrades as the
IoU threshold increases from 0.5 to 0.95. A steep drop indicates poor localisation.

**Pass Gate** — a run passes if `mAP@0.5 >= 0.75`. Failing runs are flagged in the
documentation and CHANGELOG.

**STAL Flag** — raised when `small_object_map50[cls] < per_class_map50[cls] - 0.15` for
any class, indicating that small-object detection needs attention (e.g. STAL augmentation).

## Run Comparison Guide

**Triggering a comparison:**

```bash
anti-uav compare training/run_20260101_* --output comparison/
```

Or programmatically:

```python
from anti_uav.comparator import compare_runs
report = compare_runs(run_dirs, output_dir=Path("comparison/"))
```

**Reading the report:**

- `comparison/comparison_report.md` — Markdown table of all completed runs ranked by
  `mAP@0.5:0.95` descending. Includes `small_object_map50` and `false_positive_rate` columns.
- `comparison/comparison_report.csv` — same data in CSV format for spreadsheet analysis.
- `comparison/iou_sensitivity.png` — IoU sensitivity plot for the best run.

**Identifying the best model:**

The first row of the comparison table is the best run (`best_run_id` in `ComparisonReport`).
Load its `best.pt` for deployment. Review the actionable improvement suggestions at the
bottom of the Markdown report before discarding lower-ranked runs.

## Troubleshooting

**VRAM Out-of-Memory (OOM)**

- Reduce `batch` size in `train_config.yaml` (e.g. from 16 to 8 or 4).
- Enable AMP (`amp: true`) to use mixed-precision training.
- Switch to a smaller model variant (e.g. `yolo26n` instead of `yolo26s`).
- On Kaggle Dual-T4, ensure `device: "0,1"` is set in the generated notebook.

**Class Imbalance Warnings**

- Warnings fire when the ratio between the most and least frequent class exceeds 5:1.
- Collect more images for under-represented classes, or apply weighted sampling.
- The augmentation advisor in the inspection report provides specific recommendations.

**Failed Colab / Kaggle Uploads**

- Re-run `anti-uav colab retry-uploads` to retry only the files listed in `UploadManifest.failed`.
- Check that OAuth2 credentials are valid (`~/.config/anti_uav/credentials.json`).
- For Kaggle, verify `~/.kaggle/kaggle.json` contains a valid API token.
- Ensure the target Drive folder or Kaggle dataset slug exists before uploading.

**Unmapped Classes**

- `UnmappedClassError` is raised before any file is modified when unknown class names are found.
- Add the unknown class name to your `mapping.json` file, mapping it to one of
  `Bird`, `Drone`, or `UAV`.
- Re-run `anti-uav normalize` after updating the mapping.

## Glossary

| Term | Definition |
|---|---|
| **Bird** | One of the three canonical detection classes; represents naturally occurring birds that may trigger false positives in UAV detection systems. |
| **Drone** | One of the three canonical detection classes; represents small consumer or commercial unmanned aerial vehicles. |
| **UAV** | Unmanned Aerial Vehicle — one of the three canonical detection classes; broader category including military-grade platforms. Also used as the general term for all airborne unmanned vehicles in this project. |
| **mAP** | Mean Average Precision — the primary object detection metric, computed as the mean of per-class Average Precision values. |
| **IoU** | Intersection over Union — ratio of the overlap area to the union area of a predicted and ground-truth bounding box. Used as the threshold for counting a detection as correct. |
| **STAL** | Small-Target Augmentation Layer — a specialised augmentation strategy that improves detection of small objects by synthesising additional small-object training examples. |
| **AMP** | Automatic Mixed Precision — a training technique that uses 16-bit floating point where possible to reduce VRAM usage and speed up training without significant accuracy loss. |
| **MuSGD** | Momentum SGD with custom scheduling — the default optimiser used in this project's training profiles. |
| **DUT Anti-UAV** | Dalian University of Technology Anti-UAV benchmark dataset — one of the primary evaluation benchmarks referenced in the Validation Summary section of run documentation. |
| **VisDrone** | A large-scale benchmark dataset for drone-based object detection and tracking, used as a secondary evaluation reference in run documentation. |
"""


def generate_manual(root: Path) -> Path:
    """Write MANUAL.md at project root with all 8 required sections.

    Returns path to MANUAL.md.
    """
    out = root / "MANUAL.md"
    atomic_write(out, _MANUAL_CONTENT)
    return out
